name: SimgaSigmaOnTheWall

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_371A92BD116542B6B8731485996D49AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_21DD53A250A54CFF80920ACBAB9589B8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7DC89B6DCAFE46039E21391C3945BB72 }}
          
      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "TENZIPAPI"
          slot-name: "Production"
          package: .

         
