name: SimgaSigmaOnTheWall

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID}}
          subscription-id: ${{ secrets.SUBSCRIPTIONS_ID}}
          tenant-id: ${{ secrets.TENANT_ID}}
          
          
      - name: Deploy WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "TENZIPAPI"
          slot-name: "Production"
          package: .

         
